Repository Valor6800/FRC-6800-2023-code, pull requests merged in 2023-04, with the labels that each got.

#155 Driver purple
  src/main/cpp/subsystems/Elevarm.cpp
  src/main/cpp/subsystems/Intake.cpp
Labels: Ready

#156 fix wrist CANcoder
  src/main/cpp/subsystems/Elevarm.cpp
  src/main/include/subsystems/Elevarm.h
Labels: Ready

#157 Feat(adas):Mid and High Pipeline switching
  src/main/cpp/subsystems/Drivetrain.cpp
  src/main/include/subsystems/Drivetrain.h
Labels: Ready

#158 reduced rotate PID, reduced acceleration
  src/main/cpp/subsystems/Elevarm.cpp
Labels: Ready

#160 Carriage bounding logic for High scoring
  src/main/cpp/subsystems/Elevarm.cpp
  src/main/cpp/subsystems/ValorSwerve.cpp
Labels: Needs Testing

#165 Feat: Setpoint Jogger
  src/main/cpp/subsystems/Elevarm.cpp
  src/main/include/subsystems/Elevarm.h
Labels: Ready

#167 fix:Worlds Arm Tuning
  src/main/cpp/subsystems/Elevarm.cpp
Labels: Do Not Merge, Needs Testing

#172 Fix: Toppled Cone and Upright Cone setpoints
  scripts/auto/autos/elevarmAutoTest.csv
  src/main/cpp/Robot.cpp
  src/main/cpp/subsystems/Elevarm.cpp
  src/main/cpp/subsystems/Intake.cpp
  src/main/cpp/subsystems/ValorSwerve.cpp
Labels: Ready

#173 jogger-update
  src/main/cpp/subsystems/Elevarm.cpp
Labels: Ready

#175 Fix(setpoints): comp bot tuning of pickup positions cone.
  src/main/cpp/subsystems/Elevarm.cpp
Labels: Ready

#177 fix:new cancoder values
  src/main/cpp/subsystems/Elevarm.cpp
Labels: Ready

#180 fix: Limelight bug + Setpoint tuning
  src/main/cpp/subsystems/Drivetrain.cpp
  src/main/cpp/subsystems/Elevarm.cpp
Labels: Ready
